---
S1:
L1:
- S1
L2:
- S1
R1: 
- L1
R2: 
- L1
R3: 
- L1
R4: 
- L1
R5: 
- L1
CC1: 
- L1
CC2: 
- L1
CC3: 
- L1
CC4: 
- L1
CC5: 
- L1
CC6: 
- L1
CC7: 
- L1
CC8: 
- L1
CC9: 
- L1
CC10: 
- L1
CC11: 
- L1
CC12: 
- L1
CC13: 
- L1
UP1: 
- L1
UP2: 
- L1
UP3: 
- L1
UP4: 
- UP3
UP5: 
- L1
UP6: 
- L1
UP7: 
- L1
UP8: 
- L1
M1: 
- L1
M2: 
- M1
M3: 
- M1
M4: 
- M1
M5: 
- M1
M6: 
- M1
M7: 
- L1
M8: 
- M7
M9: 
- L1
M10:
- L1
M11: 
- M7
M12: 
- M10
M13: 
- M7
M14: 
- M7
M15: 
- M10
M16: 
- L1
M17: 
- L1
M18: 
- L1
M19: 
- M18
M20: 
- M10
M21: 
- M10
