---
startup-ca.spec.js: true
login-1-ca.spec.js: true
login-2-ca.spec.js: true
filter-btn-click-ca.spec.js: false
subFilter-click-ca.spec.js: false
apply-filters-ca.spec.js: false
multiple-filters-ca.spec.js: false
export-btn-click-ca.spec.js: true
export-spreadSheet-ca.spec.js: false
items-presence-ca-1.spec.js: true
item-presence-ca-2.spec.js: true
3dots-btn-click-ca.spec.js: true
itemCard-display-ca.spec.js: true
search-by-itemID-ca.spec.js: true
seacrh-by-walmartItemNuber-ca.spec.js: false
search-by-GTIN-ca.spec.js: true
itemConfigurationOverView-ca.spec.js: true
checkbox-click-ca.spec.js: true
product-details-ca.spec.js: true
upload-btnClick-ca.spec.js: true
next-btnClick-ca.spec.js: true
test/e2e/canada/maintenance/main-btnclick-ca.spec.js: true
test/e2e/canada/maintenance/product-content/gtin.spec.js: true
test/e2e/canada/maintenance/product-content/isbn.spec.js: false
test/e2e/canada/maintenance/store-attributes/st-win.spec.js: false
test/e2e/canada/maintenance/imagery/btnclick.spec.js: true
test/e2e/canada/maintenance/imagery/upload-btnClick.spec.js: true